"use client";

// import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from './components/header';
import Footer from "./components/footer";
import { hotjar } from 'react-hotjar';
import { useEffect } from 'react';
import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Mactriq Technologies",
//   // description: "Generated by create next app",
// };

const metadata = {
  title: "Mactriq Technologies",
};

export default function RootLayout({children,}: Readonly<{children: React.ReactNode;}>) {


  interface HotjarConfig {
    id: number;
    sv: number;
    debug?: boolean;
    nonce?: string;
  }

  useEffect(() => {
    const hotjarConfig: HotjarConfig = {
      id: 3763416,
      sv: 6
    };

    hotjar.initialize(hotjarConfig);
  }, []);



  return (
    <html>
    <head>
        <Script
          async
          src="https://www.googletagmanager.com/gtag/js?id=G-5970L2LGXZ"
          />
        <Script id="google-analytics">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', 'G-5970L2LGXZ');
          `}
        </Script>
    </head>
      <body className="bg-white {inter.className}">
        <Header/>
          {children}
        <Footer/>
      </body>
    </html>
  );
}
